### PR TITLE
Add configurable hotkeys for opening the emulator menus and temporarily disabling the framelimiter.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
I'm not super happy with how the frame limiter override is implemented but it works, meh.

Playing some JRPGs on 3DS with hotkey to quadruple the framerate is pretty nice, really.

### CODE REVIEW

**Comment by bubble2k16** [comment]
I didn't know what was the best way... so I just did something that "just works" :) What will be better way to do this?

**Comment by AdmiralCurtiss** [comment]
Oh I mean my own disable-the-framelimiter code, not the original one. But that said, it probably is indeed not the best way, because sleep() tends to be inconsistent -- not sure if this also applies to the 3DS, but on most systems, calling sleep() only guarantees that you will not execute for at least that many units of time, but never guarantees that you will actually resume directly after those units of time are over. In other words, sleep(1ms) could sleep for longer than 1ms depending on how threads are scheduled, at least on Windows and Linux.

**Comment by AdmiralCurtiss** [comment]
This does appear to be the case for 3DS too, according to the libctru doc: https://smealum.github.io/ctrulib/svc_8h.html#ae1fad9317c81076e1394a376ab27c720

Note the 'minimum'.

**Comment by bubble2k16** [comment]
> Oh I mean my own disable-the-framelimiter code, not the original one. But that said, it probably is indeed not the best way, because sleep() tends to be inconsistent.

Yup I am aware of the drawbacks. But I didn't want to have those edge cases where emulating some frames just happens to be a little slower and narrowly misses vblank, but we have to drop skip 1 frame for that. That's why I didn't use the vblank syncing. 

Trade-off I guess. :)

Turns out a small number of highly sensitive users may find the non-consistent frame rate due to the lack of vblank syncing extremely disturbing.

By the way, I decided to modify the button mapping mechanism you did (which was originally SNES -> 3DS buttons). I turned it into 3DS buttons -> SNES buttons instead. At least it will be more consistent with the UI for Emus for 3DS. I made some code changes in my own quick (and oft hardcoded style), hope you don't mind!

[Also added some of those "Apply to All Games" settings, and rapid fire rate that I also had in my Emus for 3DS too]

And good job with the objectification of SMenuItem and SMenuTabs. Was struggling initially whether to implement classes or structs. Eventually decided to do it the C way (no classes) since the rest of the codes were pretty much C. Proper OOP was probably what I should have done from the get-go, so thanks for doing that for me. 👍

**Comment by AdmiralCurtiss** [comment]
Rebased on new changes, haven't tested again yet though.

**Comment by bubble2k16** [comment]
By the way this implementation works good enough to merge into the master?

**Pull request merged**
